In [15]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [16]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
### some sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### 1. ONE HOT ENCODING 

In [39]:
#  in order to convert sentences to vectors, we have to initialize vocabulary size (it is a hyper parameter)
voc_size = 10000 # vocab size can be anything
# increasing in vocab size qill take processing time more


In [40]:
onehot_rep = [one_hot(words, voc_size) for words in sent]
print (onehot_rep)

[[5064, 9367, 7664, 3695], [5064, 9367, 7664, 6406], [5064, 9586, 7664, 5648], [8472, 1045, 8693, 7400, 3812], [8472, 1045, 8693, 7400, 9405], [3426, 5064, 8061, 7664, 5475], [7704, 2853, 3054, 7400]]


### Word Embedding Representation

### 2. Post Padding
pad sequence will do: all the vectors , it will make it equal length

In [41]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [42]:
import numpy as np

In [43]:
## we need to make length of all sentences same.
## let us assume the max sentence length be 8 (padding saequence: adding zeros at last or at the first)
max_sentence_len = 8
embeded_docs = pad_sequences(onehot_rep, padding = 'pre', maxlen = max_sentence_len)  # see more about this function-->'pre', 'post'
print(embeded_docs)

[[   0    0    0    0 5064 9367 7664 3695]
 [   0    0    0    0 5064 9367 7664 6406]
 [   0    0    0    0 5064 9586 7664 5648]
 [   0    0    0 8472 1045 8693 7400 3812]
 [   0    0    0 8472 1045 8693 7400 9405]
 [   0    0    0 3426 5064 8061 7664 5475]
 [   0    0    0    0 7704 2853 3054 7400]]


In [44]:
# 10 featuire dimensions
dim = 10

In [45]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = max_sentence_len))
model.compile('adam','mse')

In [46]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [50]:
 embeded_docs[0]  # first sentence

array([   0,    0,    0,    0, 5064, 9367, 7664, 3695])

In [49]:
model.predict(embeded_docs[0]) # every vector in first sentence is represented by another vector

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 425ms/step


array([[-0.04668647, -0.01064118,  0.02858592, -0.00982483, -0.01446036,
        -0.00809491,  0.00784592,  0.00967282, -0.03606101, -0.02050449],
       [-0.04668647, -0.01064118,  0.02858592, -0.00982483, -0.01446036,
        -0.00809491,  0.00784592,  0.00967282, -0.03606101, -0.02050449],
       [-0.04668647, -0.01064118,  0.02858592, -0.00982483, -0.01446036,
        -0.00809491,  0.00784592,  0.00967282, -0.03606101, -0.02050449],
       [-0.04668647, -0.01064118,  0.02858592, -0.00982483, -0.01446036,
        -0.00809491,  0.00784592,  0.00967282, -0.03606101, -0.02050449],
       [ 0.01222362, -0.01512231, -0.04780462,  0.01302919, -0.04667025,
         0.04856647, -0.04615533,  0.00501518,  0.0349838 ,  0.03685833],
       [ 0.0412568 ,  0.01980566, -0.03875377, -0.01291258, -0.01834012,
         0.02275516,  0.01322177, -0.02994998,  0.04160792, -0.00084656],
       [ 0.02573438,  0.01324404, -0.04689125, -0.04379712, -0.02408981,
         0.03460547, -0.04018555,  0.0442105 